name: babyai
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.6
    - pytorch=1.4
    - numpy
    - blosc
    - pip
    - pip:
        - "git+https://github.com/tttyuntian/gym.git@abstract-state-seqmodel"
        - scikit-build
