name: babyai
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.6
    #- python=3.7
    - pytorch=1.4
    - numpy
    - blosc
    - pip
    - pip:
        - gym
        - scikit-build
